/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.threadTests;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        Dummy dummy=new Dummy();
        dummy.doImportantStuff1();
        dummy.doImportantStuff2();
        dummy.doImportantStuff3();
        System.out.println("The end");
    }
}
